set(ARCHCFLAGS          "-Wstrict-prototypes -Wno-attributes -Wno-unknown-pragmas -Wno-psabi -mabi=aapcs")
set(ARCHCPUFLAGS        "-mlittle-endian -march=armv7e-m -mtune=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -Wa,-mthumb -Wa,-mimplicit-it=always")
set(ARCHCXXFLAGS        "-Wno-attributes -Wno-unknown-pragmas -Wno-psabi -fno-exceptions -fcheck-new -fno-rtti")
set(ARCHPICFLAGS        "-fpic -msingle-pic-base -mpic-register=r10")
set(ARCHWARNINGS        "")
set(ARCHWARNINGSXX      "")
set(ARCHOPTIMIZATION    "-Os -fno-strict-aliasing -fomit-frame-pointer -fno-common -Wall -Wshadow -Wundef -ffunction-sections -fdata-sections")
set(CROSSDEV            "arm-none-eabi-")
set(CMAKE_C_COMPILER    "arm-none-eabi-gcc")
set(CMAKE_CXX_COMPILER  "arm-none-eabi-g++")
set(CMAKE_LINKER        "arm-none-eabi-ld")
set(CMAKE_OBJCOPY       "arm-none-eabi-objcopy")
set(CMAKE_OBJDUMP       "arm-none-eabi-objdump")
set(NXFLATLDFLAGS1      "-r -d -warn-common")
set(NXFLATLDFLAGS2      "-r -d -warn-common -T/home/SONY/s1000325098/Repos/spresense/nuttx/binfmt/libnxflat/gnu-nxflat-pcrel.ld -no-check-sections")
set(OBJEXT              ".o")
set(LIBEXT              ".a")
set(EXEEXT              "")
set(HOSTCC              "gcc")
set(HOSTINCLUDES        "")
set(HOSTCFLAGS          "-Wall -Wstrict-prototypes -Wshadow -Wundef -g -pipe")
set(HOSTLDFLAGS         "")
set(HOSTEXEEXT          "")
set(LDNAME              "ramconfig-new.ld")
set(LDELFFLAGS          "-r -e main -T /home/SONY/s1000325098/Repos/spresense/nuttx/binfmt/libelf/gnu-elf.ld")
set(EXTRA_LIBS       "/home/SONY/s1000325098/spresenseenv/usr/bin/../lib/gcc/arm-none-eabi/10.3.1/thumb/v7e-m+fp/hard/libgcc.a /home/SONY/s1000325098/spresenseenv/usr/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libm.a -lmodules")
set(EXTRA_OBJS       "")
set(HEAD_OBJ         "")
set(LDENDGROUP       "")
set(LDFLAGS          "-nostdlib --gc-sections --cref -Map=/home/SONY/s1000325098/Repos/spresense/nuttx/nuttx.map")
set(LDSTARTGROUP     "")
set(LDLIBS     "-lsched -ldrivers -lboards -lc -lmm -larch -lapps -lfs -lbinfmt -lboard -lboard ")
