/* version.h -- Autogenerated! Do not edit. */

#ifndef __INCLUDE_NUTTX_VERSION_H
#define __INCLUDE_NUTTX_VERSION_H

#define CONFIG_VERSION_STRING "12.3.0"
#define CONFIG_VERSION_MAJOR 12
#define CONFIG_VERSION_MINOR 3
#define CONFIG_VERSION_PATCH 0
#define CONFIG_VERSION_BUILD "SDK3.2.0-186214b-dirty"

#define CONFIG_VERSION ((CONFIG_VERSION_MAJOR << 16) |\
                        (CONFIG_VERSION_MINOR << 8) |\
                        (CONFIG_VERSION_PATCH))

#endif /* __INCLUDE_NUTTX_VERSION_H */
